// =============================================================================
// Newsletters — the reader's own aggregated email newsletters, surfaced in the
// Home news feed under a "Newsletter" label.
//
// Source: newsletters forwarded (via a Gmail filter) to the connected mailbox
// skaidrive2@gmail.com — Bloomberg (Money Stuff etc.), The Economist, Legal
// Business, JP Morgan, Thomson Reuters, Mailbrew and others. They are pulled
// from Gmail through the connector, parsed, and written here as feed items.
// This list is regenerated on each refresh.
//
// We keep only the headline, a one-line topic summary, the publication/author
// and the newsletter's own "read online" link — never the full article body.
// This deployment sits behind Cloudflare Access (single reader), so the list is
// personal to it.
//
// PUBLISHERS maps a sender address/domain to a display name (used by the refresh
// routine); extend it as new newsletters are added.
export const PUBLISHERS = {
  "news.bloomberg.com": "Bloomberg",
  "e.economist.com": "The Economist",
  "legalbusiness.co.uk": "Legal Business",
  "pb.jpmorgan.com": "JP Morgan Private Bank",
  "mail.sailthru.com": "Thomson Reuters",
  "thomsonreuters.com": "Thomson Reuters",
  "mailbrew.com": "Mailbrew",
  "cntraveller.com": "Condé Nast Traveller",
  "mail.nonbillable.co.uk": "Non-Billable",
  "newsletter.mail.gs.com": "Goldman Sachs",
  "businesspost.ie": "Business Post",
  "cf.com": "Chatham Financial",
  "guggenheiminvestments.com": "Guggenheim Investments",
  "newsletter.newyorker.com": "The New Yorker",
  "pe-insights.com": "Private Equity Insights",
  "getmatter.com": "Matter",
  "editorial.theguardian.com": "The Guardian",
  "taxpolicy.org.uk": "Tax Policy Associates",
  "preqin.blackrock.com": "Preqin",
  "infos.lemonde.fr": "Le Monde",
  "jpmpb.jpmorgan.com": "JP Morgan Private Bank",
  "the42.ie": "The 42",
  "equitypartner.substack.com": "Equity Partner",
};

export const NEWSLETTERS = [
  {
    id: "nl-bbg-authoralert-odeylifetimeban-20260915",
    publication: "Bloomberg",
    author: "Nishant Kumar",
    series: null,
    title: "Crispin Odey's Lifetime Ban Blocks Routes Back to City of London",
    date: "2026-09-15",
    time: "07:11",
    summary: "The hedge fund manager was accused of sexual misconduct stretching back years, and barred from finance by the Financial Conduct Authority.",
    url: "https://www.bloomberg.com/news/articles/2026-09-15/crispin-odey-s-lifetime-ban-blocks-routes-back-to-city-of-london",
  },
  {
    id: "nl-bbg-morningbriefingeurope-trumpdismissesairisks-20260915",
    publication: "Bloomberg",
    author: "Victoria Batchelor",
    series: "Morning Briefing Europe",
    title: "Trump dismisses AI risks as safety warnings mount",
    date: "2026-09-15",
    time: "06:26",
    summary: "Trump dismisses AI fears as warnings mount, the 10-year Treasury yield hits its highest since 2007, and oil pushes higher on Saudi pipeline disruption.",
    url: "https://www.bloomberg.com/news/newsletters/2026-09-15/trump-dismisses-ai-risks-as-safety-warnings-mount",
  },
  {
    id: "nl-economist-worldinbrief-scotuspostalvote-20260915",
    publication: "The Economist",
    author: null,
    series: "The World in Brief",
    title: "The World in Brief: SCOTUS rejects Trump’s postal-vote rules",
    date: "2026-09-15",
    time: "05:34",
    summary: "SCOTUS keeps Trump's mail-in voting curbs blocked, the ten-year Treasury yield tops 5%, and Trump dismisses AI-safety calls ahead of Amodei and Altman's Salesforce appearance.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-bbg-pointsofreturn-marketsblinked5pct-20260915",
    publication: "Bloomberg",
    author: "Richard Abbey",
    series: "Points of Return",
    title: "Markets blinked at 5% yields. They'll be back",
    date: "2026-09-15",
    time: "05:00",
    summary: "Bond yields still have higher to rise.",
    url: "https://www.bloomberg.com/opinion/newsletters/2026-09-15/markets-blinked-at-5-yields-they-ll-be-back",
  },
  {
    id: "nl-newyorker-weekly-horsemanviolentrevenge-20260915",
    publication: "The New Yorker",
    author: "Ian Parker",
    series: "The Weekly",
    title: "A Horseman's Violent Revenge",
    date: "2026-09-15",
    time: "00:41",
    summary: "A prominent dressage trainer shot a belligerent student—and now maintains that he's the real victim.",
    url: "https://www.newyorker.com/magazine/2026/09/21/the-violent-feud-that-shocked-the-horse-world",
  },
  {
    id: "nl-reuters-tradingday-aipocalypsenow-20260914",
    publication: "Thomson Reuters",
    author: "Jamie McGeever",
    series: "Trading Day",
    title: "AI-pocalypse now",
    date: "2026-09-14",
    time: "22:00",
    summary: "Risk off.",
    url: "https://www.reuters.com/business/what-amodei-altman-musk-have-said-about-ai-risks-stoking-doom-fears-2026-09-14/",
  },
  {
    id: "nl-cf-marketupdate-energyshockfed-20260914",
    publication: "Chatham Financial",
    author: null,
    series: "Market Update",
    title: "The energy shock meets the Fed",
    date: "2026-09-14",
    time: "19:42",
    summary: "Brent crude rose 8.65% last week to $104.61, while the 10-year Treasury yield climbed 16 basis points to 4.96%, tightening financial conditions.",
    url: "https://go.cf.com/e3t/Ctc/ZZ+113/d5Z2Pb04/MW6NprFzDM9W460FR_7D6vzcW7Wb0M15TYx3_N72QT-K3prCCW7Y8-PT6lZ3m8N24cg3ZB_JbwN3CNnVGT81PGW6KRJQc8D1nszW7J0JTR6K4cmDN61lZJG4fgpYVD7Skf2gn9gmW7jxmKx6dwdGnW3hc_l97pzYPhN84gZL_VQtzHW5zYbcy9hyYbzW4kdf3c2kHddNW3fxwb_3S3WJMW8wxs7r6H9MqFW7-Q3BP7XKF44W2SfrDv5bJSsnW3nSrwY5HL3fcW71rWyc5tfclcVrVpV84Z7q0_W8f1Pgw5mZnv8N2F-gRpChYf6W7crbsl9flZfbF4Ryw-nJ9vcW5mSTv52W3rrZW8tMwKN3M07LrW6Sm1_G1f8ZfZW6p-66x3Mmp7RdTh9Wn04",
  },
  {
    id: "nl-bbg-moneystuff-ailabsstop-20260914",
    publication: "Bloomberg",
    author: null,
    series: "Money Stuff",
    title: "Money Stuff: AI Labs Want Someone to Stop Them",
    date: "2026-09-14",
    time: "19:42",
    summary: "Lockups, annuities, pre-K, exits.",
    url: "https://bloom.bg/4rg8tR4",
  },
  {
    id: "nl-lemonde-lebrief-lepen2027-20260914",
    publication: "Le Monde",
    author: null,
    series: "Le Brief",
    title: "Enquête électorale présidentielle 2027 : Marine Le Pen entame la campagne sur un socle inédit au cœur d’un électorat inquiet et en colère",
    date: "2026-09-14",
    time: "17:34",
    summary: "La candidate du RN bénéficie d’intentions de vote inédites dans l’enquête électorale réalisée pour Le Monde.",
    url: "https://infos.lemonde.fr/optiext/optiextension.dll?ID=XsIPLy64Bocp-LmSKiFaPX3oTQNviRrfIRQ1WteI08tm8qAmx_FyCtGzI8qhUGFSwMdZzpA0yuG_XR0d0h9B2YGoxfXbf0yO",
  },
  {
    id: "nl-legalbusiness-offshorefirminvestment-20260914",
    publication: "Legal Business",
    author: null,
    series: null,
    title: "Trio of law firms advise as latest offshore firm takes investment",
    date: "2026-09-14",
    time: "16:01",
    summary: "Deal marks second offshore firm to take external investment in just six weeks.",
    url: "https://email.legalbusiness.co.uk/c/1dXnNWY81p0qdGlQUYd8us9Fhlt7",
  },
  {
    id: "nl-preqin-firstclose-europedefense-20260914",
    publication: "Preqin",
    author: null,
    series: "First Close",
    title: "Defense investment means a great deal to Europe",
    date: "2026-09-14",
    time: "12:35",
    summary: "Changing geopolitical context triggers a shift toward defense investment opportunities in Europe for private equity and VC, though the region still trails the US and APAC in AUM.",
    url: "https://go.preqin.com/webmail/909852/2169604361/a37b7380374cf2f3d0f926883036705c145c47a1b3fb9947952755ee7607cff9",
  },
  {
    id: "nl-bbg-econdaily-bessentsaibeefs-20260914",
    publication: "Bloomberg",
    author: "Chris Anstey",
    series: "Economics Daily",
    title: "Economics Daily: Bessent's AI beefs",
    date: "2026-09-14",
    time: "12:04",
    summary: "Treasury chief wants no pause in AI development, and blasts AI firms over their communication, even as leaders of the biggest US AI platforms call for a slowdown.",
    url: "https://www.bloomberg.com/news/newsletters/2026-09-14/bessent-touts-american-ai-superiority-but-has-beefs-with-its-champs",
  },
  {
    id: "nl-bbg-marketsdaily-aiboomquestion-20260914",
    publication: "Bloomberg",
    author: null,
    series: "Markets Daily",
    title: "Markets Daily: AI boom in question",
    date: "2026-09-14",
    time: "11:16",
    summary: "AI bellwethers from SoftBank to Nvidia slide after industry leaders call for a slowdown, adding to jitters over oil, a 5% Treasury yield and the Fed's pivotal week.",
    url: "https://www.bloomberg.com/news/newsletters/2026-09-14/risk-of-ai-slowdown-prompts-angst-among-tech-investors",
  },
  {
    id: "nl-legalbusiness-sullivancromwellabudhabi-20260914",
    publication: "Legal Business",
    author: null,
    series: null,
    title: "Sullivan & Cromwell launches in Abu Dhabi with Latham Middle East corporate chair",
    date: "2026-09-14",
    time: "11:31",
    summary: "Launch marks the firm's 14th office globally and first in the Middle East.",
    url: "https://email.legalbusiness.co.uk/c/1dX2YD5WMKagT6eREJjabwYXChIq",
  },
  {
    id: "nl-nonbillable-citylawyerpleadsnotguilty-20260914",
    publication: "Non-Billable",
    author: null,
    series: null,
    title: "City lawyer pleads not guilty",
    date: "2026-09-14",
    time: "09:06",
    summary: "Former City M&A lawyer Richard Bloomfield pleads not guilty to insider dealing over Goodwin's Seraphine take-private, as Latham buys Nvidia GPUs to build its own in-house AI stack.",
    url: "https://www.nonbillable.co.uk/news/city-lawyer-pleads-not-guilty-to-insider-dealing-charges-richard-bloomfield",
  },
  {
    id: "nl-businesspost-anthropicdublinambitions-20260914",
    publication: "Business Post",
    author: null,
    series: "CRE",
    title: "Anthropic’s huge Dublin ambitions",
    date: "2026-09-14",
    time: "08:00",
    summary: "Anthropic’s Dublin office hunt reveals huge ambitions for Irish jobs, plus Johnny Ronan’s RGRE pitches a hotel above Bewley’s.",
    url: "https://bpm.businesspost.ie/w/JRvWWjanSo3LAEBad7J763UQ/Pe5PTEw0pLHXiV2kox0pPw/763FBzUXofkJWC2uA1P2GYhw",
  },
  {
    id: "nl-bbg-morningbriefingeurope-stocksdropai-20260914",
    publication: "Bloomberg",
    author: "Lily Nonomiya",
    series: "Morning Briefing Europe",
    title: "Stocks drop on AI worries",
    date: "2026-09-14",
    time: "07:07",
    summary: "Stocks tumble on AI slowdown concerns and oil jumps as Middle East woes deepen, while Sweden's election hangs on the final count.",
    url: "https://www.bloomberg.com/news/newsletters/2026-09-14/stocks-decline-after-call-to-slow-ai-development",
  },
  {
    id: "nl-economist-worldinbrief-trumpaidismiss-20260914",
    publication: "The Economist",
    author: null,
    series: "The World in Brief",
    title: "The World in Brief: Donald Trump dismisses AI warnings",
    date: "2026-09-14",
    time: "06:12",
    summary: "Trump dismissed AI-safety warnings from Anthropic's Dario Amodei as overblown, as Sweden's election came down to a one-seat margin and Brent crude jumped past $108 on renewed Houthi attacks.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-bbg-pointsofreturn-warshratestrap-20260914",
    publication: "Bloomberg",
    author: "John Authers",
    series: "Points of Return",
    title: "Warsh talked himself into a rates trap",
    date: "2026-09-14",
    time: "05:02",
    summary: "No improvement leaves no choice but hike.",
    url: "https://www.bloomberg.com/opinion/newsletters/2026-09-14/inflation-warsh-talked-the-fed-into-a-rates-trap",
  },
  {
    id: "nl-bbg-authoralert-greecehedgefundelite-20260913",
    publication: "Bloomberg",
    author: "Nishant Kumar",
    series: null,
    title: "From Bailout to Mayfair Rival: Greece Lures Hedge Fund Elite",
    date: "2026-09-13",
    time: "11:24",
    summary: "Some of the world's top hedge funds opening Athens offices was the result of a plan nearly a year in the making by officials in the Greek capital.",
    url: "https://www.bloomberg.com/news/articles/2026-09-13/from-bailout-to-mayfair-rival-greece-lures-hedge-fund-elite",
  },
  {
    id: "nl-guardian-therecap-weekinsport-20260913",
    publication: "The Guardian",
    author: null,
    series: "The Recap",
    title: "Pochettino, Bunting and the story of Lumpy Stevens",
    date: "2026-09-13",
    time: "07:01",
    summary: "This week's editors' picks in sport: England's Women's Rugby World Cup win over Canada, foul-mouthed Ryder Cup abuse of McIlroy, and Pochettino says he's 'always open' to a Tottenham return.",
    url: "https://www.theguardian.com/sport",
  },
  {
    id: "nl-bbg-thebrink-livgolflossloophole-20260912",
    publication: "Bloomberg",
    author: "Jonathan Randles",
    series: "The Brink",
    title: "The Brink: LIV Golf's loss loophole",
    date: "2026-09-12",
    time: "16:00",
    summary: "When red ink turns into big tax benefits: BC Partners looks to turn LIV Golf's bankruptcy-era operating losses into tax shelter value as it tries to give the league a second act.",
    url: "https://www.bloomberg.com/news/newsletters/2026-09-12/liv-golf-s-big-losses-provide-fuel-for-a-second-act",
  },
  {
    id: "nl-equitypartner-biglawpaywar-20260912",
    publication: "Equity Partner",
    author: "David Morley",
    series: null,
    title: "Why BigLaw's pay war ends in equity, not cash",
    date: "2026-09-12",
    time: "10:51",
    summary: "Law firms will shift from competing on cash to offering partners lasting equity stakes in AI-powered \"firm brain\" systems that capture institutional knowledge.",
    url: "https://equitypartner.substack.com/p/why-biglaws-pay-war-ends-in-equity",
  },
  {
    id: "nl-taxpolicyassociates-touristtax-20260912",
    publication: "Tax Policy Associates",
    author: "Dan Neidle",
    series: null,
    title: "England's new tourist tax: what it raises, who pays, and what it costs",
    date: "2026-09-12",
    time: "08:11",
    summary: "An independent, open model estimating what England's proposed ~5% tourist tax on overnight stays would raise, who bears the cost, and its impact on the hospitality industry.",
    url: "https://newsletter.taxpolicy.org.uk/campaign/b97066b9-60cc-4386-aa7f-eafc829e7f97/e5358a8a-4e5b-4303-a7ce-dcf4d37cc11c",
  },
  {
    id: "nl-economist-worldinbrief-saudipipeline-20260912",
    publication: "The Economist",
    author: null,
    series: "The World in Brief",
    title: "The World in Brief: Saudi Arabia shuts East-West pipeline",
    date: "2026-09-12",
    time: "05:53",
    summary: "Saudi Arabia shuts its East-West pipeline after a wave of attacks blamed on Iraq-launched drones and a Houthi seizure of Yemen's Perim island, while US core inflation cools to 2.4% but stays too hot to stop a Fed rate rise.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-bbg-singaporeedition-talentrace-20260912",
    publication: "Bloomberg",
    author: null,
    series: "Singapore Edition",
    title: "Singapore Edition: The talent race",
    date: "2026-09-12",
    time: "02:00",
    summary: "Singapore vs Hong Kong: the rivalry that never gets old, as both cities compete harder than ever for global finance talent.",
    url: "https://www.bloomberg.com/news/newsletters/2026-09-12/singapore-vs-hong-kong-which-city-is-the-best-to-move-to",
  },
  {
    id: "nl-matter-popularweek-childhood-20260911",
    publication: "Matter",
    author: null,
    series: "Popular This Week",
    title: "10 Most Popular This Week: Have We Destroyed Childhood?",
    date: "2026-09-11",
    time: "17:17",
    summary: "This week's ten most-saved reads, led by Joshua Rothman's New Yorker essay on the vanishing of unsupervised childhood.",
    url: "https://u14128625.ct.sendgrid.net/ls/click?upn=u001.Tu2Ijs0AVAbbOOFi05GBHuSCWdZvULrvWUwfj6lZtznpOJ9-2BoEH2UiwpAUz3j2Q4HsPCt-2B3dMcWQ4vRZ7K4TDpuNu-2BjboO5JGrEAebTt3uJePpPHUpqFVuMVBU5qkDTKbQ6V_AV9-2BPRP7Uj5QvX1NLKvBo7mSghDIloonB1HrvLeIVHqAWH6timJNUuyrBmerUGYumxmqur1nBgU9SQWrQSFmCgou8c1mZXN-2Fn3tr2-2BL7da8kp5v6B8HbIkapBDlXa3LAtg0HLLCf7m-2BQjMgyu5WVSY7H-2FzP3c-2BfEE0TTPi47xzifqFUki6Ag6WwPapE5awirpNT3vcx1dw3ygm9iV0KX2xfFC6INzWcVetmb1UHXqosFj05A2mBXAJOyNBtey8s5gLBePHfOu2aK4CxYipTkYVM5eIO-2B5rOZzl8P3-2FFrnyFAIg-2BrHLvgY2-2BPBSwxzf4o",
  },
  {
    id: "nl-bbg-moneystuffpodcast-whatstheconcern-20260911",
    publication: "Bloomberg",
    author: null,
    series: "Money Stuff",
    title: "Money Stuff: The Podcast: What’s the Concern?",
    date: "2026-09-11",
    time: "17:39",
    summary: "Guest host Max Abelson on money and power, the DAT trade, meme-stock bazaars, and stock ledgers on the blockchain.",
    url: "https://bloom.bg/4nhTnYV",
  },
  {
    id: "nl-lemonde-lebrief-25ans11septembre-20260911",
    publication: "Le Monde",
    author: null,
    series: "Le Brief",
    title: "25 ans du 11-Septembre : « Nous n’oublierons jamais (…) C’est pour ça que nous nous battons aujourd’hui », dit Donald Trump lors des commémorations au Pentagone",
    date: "2026-09-11",
    time: "17:34",
    summary: "Americans mark 25 years since 9/11's 2,977 deaths; Trump breaks with the New York memorial's tradition to give a political speech at the Pentagon.",
    url: "https://infos.lemonde.fr/optiext/optiextension.dll?ID=qPXRTdgSwNkfltcutyFbacuh209Sx3wVWH0fOscWFuByqV57REOOVrQI3EHmr3B_gbRLtPLmzfZfgJnntu2zvl11kl7rl4GkQk6xS-yz",
  },
  {
    id: "nl-legalbusiness-srascrutiny-20260911",
    publication: "Legal Business",
    author: null,
    series: null,
    title: "SRA faces renewed scrutiny as LSB steps up pressure",
    date: "2026-09-11",
    time: "16:20",
    summary: "After a run of bruising law firm collapses, the SRA is facing questions over how it can up its game – and what needs to change.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMR6OtbZdENfhCSepp/wv",
  },
  {
    id: "nl-legalbusiness-sixmapartnersweilcravath-20260911",
    publication: "Legal Business",
    author: null,
    series: null,
    title: "Full details - the six M&A partners set to leave Weil for Cravath",
    date: "2026-09-11",
    time: "15:29",
    summary: "Five other partners to join corporate chair Aiello in move to Cravath.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMR6JZEgXOQdYZ5gAX/wv",
  },
  {
    id: "nl-mailbrew-fridaybrew13-20260911",
    publication: "Mailbrew",
    author: null,
    series: null,
    title: "Friday Brew #13",
    date: "2026-09-11",
    time: "13:58",
    summary: "A curated digest on the data-center backlash despite 401(k) dependence on it, Drexel Burnham as the godfather of private credit, and shorting the dollar by drinking free first-growth Bordeaux.",
    url: "https://app.mailbrew.com/stevedkennedy/friday-brew-03bEHcNb3hHB/13",
  },
  {
    id: "nl-goldmansachs-briefings-outlookforlongbonds-20260911",
    publication: "Goldman Sachs",
    author: null,
    series: "Briefings",
    title: "The Outlook for Long Bonds",
    date: "2026-09-11",
    time: "13:54",
    summary: "Goldman Sachs Research expects the fiscal concerns pushing up global bond yields to persist even as some other drivers dissipate, with gold forecast to rally amid rising volatility.",
    url: "https://clicks.newsletter.mail.gs.com/ls/click?upn=u001.o42bWkJ9Wa3U2i4KUQa27grjrLjMzQMcWfPO76LXsYLjS42I57vtTnx-2FI5PtAUNpHGBtFfDa8WOQ9O4Qt-2B8hP63FFAHKJxIqVKPEqY0OHdgGtE-2B6rQGkBlWGiQUJi6UjRtltzSktj19m9XOpEi6BUESpHB9uRq87puBng5Dd91C7-2FOjB8c91JWppOT4gHRg0-y1Y_AV9-2BPRP7Uj5QvX1NLKvBo7mSghDIloonB1HrvLeIVHq293sOX0RtBmYEmcPgr17HBGV-2FkQX49yirl9R5louU2i-2BPSoYU46Qo-2FFOOVcKy4-2Fp64WQb4BhtrjfxrjSZXEgbVhOc8bnphQ7gyuhkT6Ul40JUf8G-2B7MpKkfjYZrQ7i3Y4LxXdjgW-2FqRRirpQ59wnc0c2kT6pY8eJRzxwB0c43SLa2hs7w82FXsDX3pABckkeifFWK4YnVIRyn-2BJZ7fFyu6dsRGGPKo2vjVCh9LZBlJK-2FTuiGd7CNIZoO-2F-2BY-2FEe8GwJGDSCbVp-2BeSWDiRoBoAoHafToOk5btspDFAI41lFH8Iwm-2B3bHwIBabIZ9DF24-2BnVAHX-2B-2FVn6G68tedfVfgKaTAffKqXJ1c4Q33uyCGObFuncV0DWv-2BXiXoFwLEPGzkyH0b3RlzwPT8ALXfwwQcvlVdMIj3WHbSmvRXehozptUBterWVFIbdLyOINzKLpdmbMQ8hwjgWZ8-2F-2FU7T4vdnDsr-2F1fmTWSOXXGK2oX47ZtBZixgR3jGJljdXmF7vGjv4yQqX2zPkPuoRcEIHZReaCxiMpB-2FnROmMsPVkZVfZNXBUYw3WzMhi2EaO9bb7UKqL33bwDi1ZoU0g8-2Bj23ucNLoHkox-2F59ST43KP6Ifg8vB-2BQCwhiTCfGYTVlZnGHGjzz5RwIqanMvZial7B74dJY8WlLIKJR0w48uDbcLqcNflrEs4Kz3RQu6NAO1yDsm0Z2A-3D",
  },
  {
    id: "nl-bbg-authoralert-elancapitalgreece-20260911",
    publication: "Bloomberg",
    author: "Nishant Kumar",
    series: null,
    title: "Dimitriou's Elan Joins Hedge Funds Mulling an Office in Greece",
    date: "2026-09-11",
    time: "13:44",
    summary: "Renos Dimitriou's Elan Capital Management is exploring an Athens office, joining a cohort of hedge fund peers eyeing the Greek capital as a new base for staff.",
    url: "https://links.message.bloomberg.com/a/sc/AOdCubO_lc_s54-_Ui2BpXfXLThWp7xQouYirihN9J28rb4qE1GDtE_vMMp-qsfpRPVT0r4daJilDwNgYyuAGjRcjesuEECgeSfN5pzQ3V4LNk4IkF2SWOAl6Y5ftaLZ_yvfvH-wM1EIDDbp-1XCjOj34PhvuqjZFQqliCUs2ypsYhrGdy2CzMyzYAPl_6xIo5jJ1aQ_tyD37O6WsQm8ziXIdcQ2RGh9jJ9wfGYqVJZa4LhXkGXXClkNIjGr5de8YO2Frn6zdUIq7GCFp3E7P-hcFafjhDd2BMYhrwaOiLIMwEc7Y8uiXXgqpl3VKTearYMZMGoZaj0MNY57OQo7fLDh1fePMY19e6vtyXoLy6xxiRbb4RPGI_ThciqUOiJGdocosTdjFmkAkqNRkmXakjQxi6_GiwNyzuClhBHkCaFQwMd0vjjXF5-1Pw_DMf_8fMTnTLff6WqYpMdJRu7ujfAVhoKK20qpgWaZl2sMxw1vMmSzNiBzlXB4tbFwCASBA97dxw",
  },
  {
    id: "nl-jpmorgan-topmarkettakeaways-oilat100-20260911",
    publication: "JP Morgan Private Bank",
    author: null,
    series: "Top Market Takeaways",
    title: "Oil at $100? Not scary.",
    date: "2026-09-11",
    time: "13:30",
    summary: "Higher oil prices are back in focus, but consumers and investors appear better positioned to absorb this energy shock than past ones.",
    url: "https://go-jpmpb.jpmorgan.com/v/MzkyLUhLQy04NzYAAAGkL2vDyCAVIVx5Cv1z7xFThgPXq9FgFJgpoeROcg7hN9vV2y-H4n7_QhWPUScoWZp-9eWZ_pY=",
  },
  {
    id: "nl-bbg-parisedition-orangealert-20260911",
    publication: "Bloomberg",
    author: "Lionel Laurent",
    series: "Paris Edition",
    title: "Paris Edition: An orange alert",
    date: "2026-09-11",
    time: "12:41",
    summary: "Slowing growth and an electoral cycle mean France's economy is heading into worrisome territory, after Insee slashed its 2026 growth forecast to 0.4%.",
    url: "https://links.message.bloomberg.com/a/sc/QZX1pw8y77M6FhQDEJSD3UJxIeXPcS1etRJKHYCU_Ldi-mzLPKqyBye81SZlV0Rz5evSQwUxg4L8QEofell66f34OEpNsYhy5F84z4o95_Z-JybQeeocyTNxfHata6p0D5qwduUlyJfaIbBQudUWWNzdwEP2zM6-CvmggCZFkZMgu-2BdydB4beJWV4ZGGO6F1Pv15xqQ5Cv2UGjfromY_flRo1WorPryTXXao3T0DvXqa89mzxS5B9IWcwHiIXT7qL2f10GzlwTREI7iaXcsZs37nr6CbFyCJ9NpzyjSowqyudSIgKJYn6pmJLM5dm2PEG8hJPc75zf9at3JnHXsSESmkFS8aWw0gs6c0ap8r3n24Ff7QUW9vTmp9jdcSrYrHrYaZR7FnXwWmQjpIQKhcOvwRCTthf9SXk7WGDibssqAc9qW1KwiaHpUzz8EAX7x28XDum9z1R_yjnnhhJ6MfnF7F8Pxv_SduSEU9hpHcGfIUGBFIzDNGSJY-fpEK6gnV9UsIjq1Dh8po5UnNZNhKaRJqMUgV9lfFE",
  },
  {
    id: "nl-bbg-goingprivate-creditjengatower-20260911",
    publication: "Bloomberg",
    author: "Sinead Cruise",
    series: "Going Private",
    title: "Going Private: Credit's Jenga tower in peril",
    date: "2026-09-11",
    time: "12:08",
    summary: "Short-sellers circle as the global bond rout raises questions about risk-reward in direct lending; Andromeda's Alberto Gallo warns insurers and pensions are 'scaling a Jenga tower of debt' in the $1.8 trillion sector.",
    url: "https://links.message.bloomberg.com/a/sc/Jgv6PDelEe0FrDuBAQslGOJRXzS2yM9Il7aUopUThPzSAV-yTB5C6B4NPLOL8VcBh5AzO4mnmT6F1XnX6MnEYleyUIrpWayb02Z832yRwFA2e9c-l1EU2TmLZYkGgz3TI2hRzB6M_ftsTy8uyyCMG91TFfaaHSGXUdi2Rl74cZvR6KRyjj45UQ8R59BEAlFbrNPXZR3ikchSasfxyPzgJz63S4jdVquHeBGnfWTBVupMkCVZhieG5mGfAQq58hgWk2Li1oQSMEri2P2GUhojm8o4Zc07w78f9adagWxB8HEs8e_NFy-UdnyFgwB9_DE-i4E76HIzGWNIjHjeZFAR_aHkLub8OXIYvvFhHb-bazv0SRY_aVYYsz8amCXFfOgYYQbRhKO79rliS7SZhINhCoMRZW7HuE-DCSrKr9jGfbWRwqCfTgI1ZMMBeTXT-2rmXVjblZqV8sDGqd_6hehajsZ5PSMGJmrjJ6dusK3KVSW8Db7Niu4WS3gHQg0aV-M0BYmBRduIZrfyur1fEweWqEj02XnljPdia1FS4UkRtwo",
  },
  {
    id: "nl-bbg-econdaily-hikingseason-20260911",
    publication: "Bloomberg",
    author: "Craig Stirling",
    series: "Economics Daily",
    title: "Economics Daily: Hiking season",
    date: "2026-09-11",
    time: "12:04",
    summary: "With a second rate hike under its belt since the Iran war began, the ECB appears to be just getting into its stride as it moves to rebuild inflation-fighting credibility.",
    url: "https://links.message.bloomberg.com/a/sc/JvIRU0NUGg9PRWi-35ohNTdadIqv-yCQGqMccOnL_ky-RxRowbdZseNjUyNJMcNYgW08jzvlGtGWUi7loEdkeyhXqxQ4N34p9NYB_-DlBAZ_nYBcUZTneIGV9KhNbHeDVatP7g2PvSvr_hvNyvs46Vs6Gnte2zKxllyhVH3VohIEB3PP_-Up-5EJZMJ10NPiD3fEHrLBJw0R16GPmfIyKHs_LQqplBq2UrktVk2GmIRhU2dIXiuT4oFOdJjLyGsutKbgkwTLnm9gkqwstpfe95KBoOS_PBBXlNFl0yxzHedqDsutYsE3yw2dfz3MKLfRt6SnLTbZOcKPA2B-ghZwjoijnmlrzvSBeuRK_PpkTai0D6IluDwe-dvV8SJusiY8U2oT8JkMX-Mdbp9HqUg_qIaRzeRseL3n4FMzRi6Hml5vgxaGBHjjAqtwtO1lZKbidc7n40-wgJKa1WqBpuQ07_uKndOEzvJF5n682_igbPC5nsuhxPDBwkf9R1LyYQYKskMY6JEOZBLSudyTrp0",
  },
  {
    id: "nl-bbg-marketsdaily-worryingtimes-20260911",
    publication: "Bloomberg",
    author: null,
    series: "Markets Daily",
    title: "Markets Daily: 'Worrying times'",
    date: "2026-09-11",
    time: "11:48",
    summary: "Bond bears push 10-year Treasury yields to the cusp of 5% ahead of US inflation data, with US diesel topping $6 a gallon for the first time as traders weigh whether higher yields will finally hit stocks.",
    url: "https://links.message.bloomberg.com/a/sc/iIXvaBum6YhDw4QaPEHl1ZOG8QLYxEjERtMtQNR0OX0d9pjxnjcFcjJlVn2xTl1C4JFF1G2z5WMeswFxMUuY1ayK1XJFNiBKeDqmyohtj8wg7K-isd1TdZYG1J8r6k-PhmvW9cQz6RoYMqmnLZdUdTnf358lVWC1BA3XHPgXlSu33cRfSnurE3ops0AKtEcUd5XW7k2FkcfN1cUIwQFi2_LZ7wj6xXDDXmtwQ0F_k2YDzS5xq0-M4w3wopRX6oIL2A43ZSJQ5xs4WmaGPLGy75zQDv8tU5uYNvsPg-n0wjZURFJSBdAA_1dH7Ao38PtnssZW48OQUA7-NMsuPKyOy-yXrOaHP7KoQH0GwIMKkMz1RmEoQpxBASbgBj2Ab0AI_j5Gj0BDj71AeYem48a__JhfbyW1gO13icCfXAq466rPGQebV8jRAhJmn_MMPYPc_AyvboHgd8h_-Zbsyru24OQVVDd50r28bSRwQm8dhCYGdZOgvJHeSm4iPiBOcWgaDXpR2NwHbaw2A0QMAbhs-o56W0vsnrotDUNGaY3VIvzq",
  },
  {
    id: "nl-legalbusiness-exgoodwininsidertrading-20260911",
    publication: "Legal Business",
    author: null,
    series: null,
    title: "Former Goodwin lawyer pleads not guilty to charges of insider trading",
    date: "2026-09-11",
    time: "11:09",
    summary: "FCA charges relate to the take-private of now-collapsed maternity-wear brand Seraphine.",
    url: "https://email.legalbusiness.co.uk/c/1dWGNJLpkQ7OzrMbl7ghEVJIlPvj",
  },
];
