// =============================================================================
// Newsletters — the reader's own aggregated email newsletters, surfaced in the
// Home news feed under a "Newsletter" label.
//
// Source: newsletters forwarded (via a Gmail filter) to the connected mailbox
// skaidrive2@gmail.com — Bloomberg (Money Stuff etc.), The Economist, Legal
// Business, JP Morgan, Thomson Reuters, Mailbrew and others. They are pulled
// from Gmail through the connector, parsed, and written here as feed items.
// This list is regenerated on each refresh.
//
// We keep only the headline, a one-line topic summary, the publication/author
// and the newsletter's own "read online" link — never the full article body.
// This deployment sits behind Cloudflare Access (single reader), so the list is
// personal to it.
//
// PUBLISHERS maps a sender address/domain to a display name (used by the refresh
// routine); extend it as new newsletters are added.
export const PUBLISHERS = {
  "withintelligence-email.com": "With Intelligence",
  "news.bloomberg.com": "Bloomberg",
  "e.economist.com": "The Economist",
  "legalbusiness.co.uk": "Legal Business",
  "pb.jpmorgan.com": "JP Morgan Private Bank",
  "mail.sailthru.com": "Thomson Reuters",
  "thomsonreuters.com": "Thomson Reuters",
  "mailbrew.com": "Mailbrew",
  "cntraveller.com": "Condé Nast Traveller",
  "mail.nonbillable.co.uk": "Non-Billable",
  "newsletter.mail.gs.com": "Goldman Sachs",
  "businesspost.ie": "Business Post",
  "cf.com": "Chatham Financial",
  "guggenheiminvestments.com": "Guggenheim Investments",
  "newsletter.newyorker.com": "The New Yorker",
  "pe-insights.com": "Private Equity Insights",
  "getmatter.com": "Matter",
  "editorial.theguardian.com": "The Guardian",
  "taxpolicy.org.uk": "Tax Policy Associates",
  "preqin.blackrock.com": "Preqin",
  "infos.lemonde.fr": "Le Monde",
  "jpmpb.jpmorgan.com": "JP Morgan Private Bank",
  "the42.ie": "The 42",
  "equitypartner.substack.com": "Equity Partner",
  "go.reuters.com": "Reuters",
  "mail.thelawyer.com": "The Lawyer",
  "morganstanley.com": "Morgan Stanley",
  "e.apollo.com": "Apollo",
  "fitchratings.com": "Fitch Ratings",
};

export const NEWSLETTERS = [
  {
    id: "nl-thelawyer-breaking-andrewmountbattenwindsorjudicialreview-20261009",
    publication: "The Lawyer",
    author: null,
    series: "Breaking News",
    title: "Breaking News: Blackfords and Matrix on call for Andrew Mountbatten-Windsor in judicial review",
    date: "2026-10-09",
    time: "12:20",
    summary: "High Court rules the February search warrants for his Sandringham and Windsor homes were unlawfully issued.",
    url: "https://r.mail.thelawyer.com/mk/mr/sh/28xHBT2OOm5aQrn4OwPr9qwiC32Ybr5qUL/4A19HOS56v7i",
  },
  {
    id: "nl-bbg-economicsdaily-ailagsasiafirst-20261009",
    publication: "Bloomberg",
    author: "Ben Holland",
    series: "Economics Daily",
    title: "Economics Daily: AI time lags",
    date: "2026-10-09",
    time: "12:09",
    summary: "The AI boom lifts Asian exporters first, with the US payoff still to come.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-09/ai-lagged-impact-helps-asia-first-with-us-last",
  },
  {
    id: "nl-apollo-dailyspark-aiinsensitivitytointerestrates-20261009",
    publication: "Apollo",
    author: "Torsten Slok",
    series: "The Daily Spark",
    title: "AI’s Insensitivity to Interest Rates Is a Problem for the Fed",
    date: "2026-10-09",
    time: "11:46",
    summary: "A rate-insensitive AI boom drains capital, power and labour from housing and autos, keeping the Fed higher for longer.",
    url: "https://click.e.apollo.com/?qs=ABp7ImQiOjUwMjQsInQiOjM5MzIsInMiOjEyfQAMAAAAAANpe0BH16Wgm9OxW4X4csZIZGsO6H1doQyqG3MvEEQ4yCbrUPKirIsOmGIGrqlP2neOHa1WGS8lEfYNaH1pxM2vnVUCQmdJHzb2ho-OINiV",
  },
  {
    id: "nl-reuters-morningbidweekend-bondsbrentbarricades-20261009",
    publication: "Thomson Reuters",
    author: null,
    series: "Morning Bid Weekend",
    title: "Bonds, Brent and barricades",
    date: "2026-10-09",
    time: "11:40",
    summary: "Weekly market recap: European bond stress, Brent volatility and record-high US equities.",
    url: "https://www.reuters.com/commentary/reuters-open-interest/",
  },
  {
    id: "nl-bbg-marketsdaily-extinctionrisk-20261009",
    publication: "Bloomberg",
    author: null,
    series: "Markets Daily",
    title: "Markets Daily: Extinction risk",
    date: "2026-10-09",
    time: "11:20",
    summary: "Anthropic IPO forces the question of how to price rogue AI risk; plus Starbucks-Chipotle synergies.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-09/anthropic-ipo-forces-question-of-how-to-price-rogue-ai-risk",
  },
  {
    id: "nl-thelawyer-newsdaily-weilzalkalitigationstar-20261009",
    publication: "The Lawyer",
    author: null,
    series: "News Daily",
    title: "Women in Business Law: How Weil's securities chief went from financial-crisis associate to litigation star",
    date: "2026-10-09",
    time: "08:25",
    summary: "Caroline Zalka now leads Weil's securities litigation team.",
    url: "https://r.mail2.thelawyer.com/mk/mr/sh/28xHBT2OOm5aQrn4OwPr9qwiC32Ybr5qUL/fFKkTXdC4Pl5",
  },
  {
    id: "nl-bbg-morningbriefingeurope-mideastreprieve-20261009",
    publication: "Bloomberg",
    author: null,
    series: "Morning Briefing Europe",
    title: "Mideast reprieve",
    date: "2026-10-09",
    time: "08:44",
    summary: "Oil falls as Trump says US will not attack Iran before the midterms.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-09/oil-falls-as-trump-says-us-will-not-attack-iran-before-midterms",
  },
  {
    id: "nl-nonbillable-kingspaldinglondongrowth-20261009",
    publication: "Non-Billable",
    author: null,
    series: null,
    title: "Inside King & Spalding's London growth push",
    date: "2026-10-09",
    time: "09:07",
    summary: "Kirkland closes the books plus a costly Simpson Thacher blunder.",
    url: "https://non-billable.beehiiv.com/p/draft-d81c",
  },
  {
    id: "nl-economist-worldinbrief-techvisabar-20261009",
    publication: "The Economist",
    author: null,
    series: "The World in Brief",
    title: "The World in Brief: Trump bars tech firms from visa programme",
    date: "2026-10-09",
    time: "06:05",
    summary: "Also: A murder case ignites fury in Okinawa.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-reuters-tradingday-paintradestrikes-20261008",
    publication: "Reuters",
    author: "Jamie McGeever",
    series: "Trading Day",
    title: "The pAIn trade strikes",
    date: "2026-10-08",
    time: "22:04",
    summary: "Spotlight turns to US payrolls.",
    url: "https://www.reuters.com/newsletters/trading-day",
  },
  {
    id: "nl-bbg-moneystuff-preipoperpetualfuturesswapetf-20261008",
    publication: "Bloomberg",
    author: "Matt Levine",
    series: "Money Stuff",
    title: "Money Stuff: Pre-IPO Perpetual Futures Swap ETF",
    date: "2026-10-08",
    time: "19:21",
    summary: "MANGOS, prime, longshots, buffet.",
    url: "https://bloom.bg/4jMk7RK",
  },
  {
    id: "nl-thelawyer-breaking-visamastercardpostbrexitclaim-20261008",
    publication: "The Lawyer",
    author: null,
    series: "Breaking News",
    title: "Visa and Mastercard face new \u00a3700m claim over post-Brexit fees",
    date: "2026-10-08",
    time: "17:35",
    summary: "Geradin Partners has launched a new class action against Visa and Mastercard, with magic circle and US firms acting for the defendants.",
    url: "https://r.mail.thelawyer.com/mk/mr/sh/28xHBT2OOm5aQrn4OwPr9qwiC32Ybr5qUL/xbhiNY3LlbXf",
  },
  {
    id: "nl-fitch-wiredaily-trucksabs-20261008",
    publication: "Fitch Ratings",
    author: null,
    series: "Fitch Wire Daily",
    title: "Fitch Wire Daily: US Truck Equipment ABS Remains Vulnerable to Cost Pressures; Access to Power to Drive Taiwan AI Data-Centre Growth; and More",
    date: "2026-10-08",
    time: "16:01",
    summary: "US truck equipment ABS cost pressures, Taiwan AI data-centre power access, Spain snap election, Italy budget framework.",
    url: "https://goto.fitchratings.com/v/NzMyLUNLSC03NjcAAAGkuwEB9CgvBVy1YJE2gM3aUiM1vCrHrTd0y4BKBQVZhYIvq2MtczXynFH52AT9r9Ck0sT1GnM=",
  },
  {
    id: "nl-legalbusiness-alert-greenambassadors-20261008",
    publication: "Legal Business",
    author: null,
    series: "Legal Business Alert",
    title: "Simpson Thacher, Travers, Winston Taylor lawyers among new UK Green Ambassadors",
    date: "2026-10-08",
    time: "15:29",
    summary: "ESG, energy transition and real estate specialists among lawyers recognised in Legal 500 guide to the sustainability agenda.",
    url: "https://www.legalbusiness.co.uk/green-ambassadors/simpson-thacher-travers-winston-taylor-lawyers-among-new-uk-green-ambassadors/",
  },
  {
    id: "nl-reuters-econworld-notjustdejavuinfrance-20261008",
    publication: "Reuters",
    author: "Mark John",
    series: "Econ World",
    title: "Not just a case of d\u00e9j\u00e0 vu in France",
    date: "2026-10-08",
    time: "14:06",
    summary: "The budgetary and political context make this different.",
    url: "https://www.reuters.com/newsletters/reuters-econ-world",
  },
  {
    id: "nl-thelawyer-breaking-legorasplitsfromrivals-20261008",
    publication: "The Lawyer",
    author: null,
    series: "Breaking News",
    title: "Legora splits from rivals over future of legal AI",
    date: "2026-10-08",
    time: "12:37",
    summary: "Legora may train open AI models for a few tasks but says going further is \u201cnot a smart idea\u201d.",
    url: "https://r.mail2.thelawyer.com/mk/mr/sh/28xHBT2OOm5aQrn4OwPr9qwiC32Ybr5qUL/MgqRPU5sfjjS",
  },
  {
    id: "nl-tpa-badenochinheritancetaxcut-20261008",
    publication: "Tax Policy Associates",
    author: "Dan Neidle",
    series: null,
    title: "Badenoch\u2019s inheritance tax cut could cost \u00a311bn \u2013 almost twice the advertised price",
    date: "2026-10-08",
    time: "12:35",
    summary: "Estimated cost of the Conservative family-home IHT exemption is \u00a37.7bn\u2013\u00a310.9bn versus the \u00a36bn claimed.",
    url: "https://newsletter.taxpolicy.org.uk/campaign/bc74ce87-4f52-4610-afd9-728fc8dd448a/fd0b23db-b61a-4813-bcbf-44577160c2d1",
  },
  {
    id: "nl-preqin-firstclose-informationtointelligence-20261008",
    publication: "Preqin",
    author: null,
    series: "First Close",
    title: "Investors connect information with intelligence for competitive advantage",
    date: "2026-10-08",
    time: "12:20",
    summary: "Information alone no longer enough for asset managers; 72% of organisations use eight or more tech platforms.",
    url: "https://go.preqin.com/webmail/909852/2197771922/10a07fc888799ba93601ccf55d4c7de31840aed202839f3c768c45aa7be76665",
  },
  {
    id: "nl-bbg-economicsdaily-chinasunbalancedstimulus-20261008",
    publication: "Bloomberg",
    author: "Chris Anstey",
    series: "Economics Daily",
    title: "Economics Daily: China’s unbalanced stimulus",
    date: "2026-10-08",
    time: "12:00",
    summary: "China’s mini-stimulus may shore up GDP while reinforcing imbalances, per JPMorgan Chase economists.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-08/china-s-stimulus-may-shore-up-gdp-while-reinforcing-imbalances",
  },
  {
    id: "nl-bbg-marketsdaily-francestressbellwether-20261008",
    publication: "Bloomberg",
    author: null,
    series: "Markets Daily",
    title: "Markets Daily: France as the stress bellwether",
    date: "2026-10-08",
    time: "11:49",
    summary: "France is the canary for global market stress; plus Treasury yield forecasts.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-08/france-is-the-bellwether-for-stress-in-global-markets",
  },
  {
    id: "nl-apollo-dailyspark-outlookfrenchspreads-20261008",
    publication: "Apollo",
    author: "Torsten Slok",
    series: "The Daily Spark",
    title: "Outlook for French Spreads",
    date: "2026-10-08",
    time: "11:46",
    summary: "Chart book on France and the ECB: French spreads over Germany at widest since 2011.",
    url: "https://click.e.apollo.com/?qs=ABl7InYiOjEsImQiOjUwMjMsInAiOiJQQyJ9AAwAAAAAA2R4DZqqpf6JGIN_PZIwPz-lVujuYXg2yLe2TskdhSJvtenKkLRyaDy7F7mfgETdrIf2lsiRPaiKgxLEs2rw2Gyw85Zb2n_0YLaOsks0wInL-QDNAs_nUw",
  },
  {
    id: "nl-withintelligence-privatecreditinsights-20261008",
    publication: "With Intelligence",
    author: null,
    series: "Private Credit Insights",
    title: "Private Credit Insights: Amundi Alpha Associates targets up to ten PC managers",
    date: "2026-10-08",
    time: "11:12",
    summary: "Weekly private credit roundup: Amundi Alpha Associates, Vista Equity $2.2bn close, M&G-backed transition credit fund.",
    url: "https://pardot.withintelligence.com/webmail/284832/3598997631/23fcdd7c20d30df223e97a343c7c91b872fd93050b0c889e2b0abf0950a7caa2",
  },
  {
    id: "nl-thelawyer-newsdaily-weilsheppardaibootcamp-20261008",
    publication: "The Lawyer",
    author: null,
    series: "News Daily",
    title: "Weil and Sheppard Mullin send lawyers to AI bootcamp",
    date: "2026-10-08",
    time: "08:16",
    summary: "Top firms have paid for their lawyers to learn how to build legal tech tools with AI.",
    url: "https://r.mail.thelawyer.com/mk/mr/sh/28xHBT2OOm5aQrn4OwPr9qwiC32Ybr5qUL/PHrdvFipQch9",
  },
  {
    id: "nl-bbg-morningbriefingeurope-strikerisks-20261008",
    publication: "Bloomberg",
    author: null,
    series: "Morning Briefing Europe",
    title: "Strike risks",
    date: "2026-10-08",
    time: "07:30",
    summary: "Oil gains on report White House is mulling Iran strikes.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-08/oil-gains-on-report-white-house-is-mulling-iran-strikes",
  },
  {
    id: "nl-economist-worldinbrief-bondselloffeases-20261008",
    publication: "The Economist",
    author: null,
    series: "The World in Brief",
    title: "The World in Brief: America\u2019s bond sell-off eases",
    date: "2026-10-08",
    time: "06:00",
    summary: "Also: The new Polar politics.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-bbg-pointsofreturn-spectacularearningsnotenough-20261008",
    publication: "Bloomberg",
    author: "John Authers",
    series: "Points of Return",
    title: "Earnings will be spectacular. It may not be enough",
    date: "2026-10-08",
    time: "05:00",
    summary: "Can profit growth like we are likely to see this season be sustained?",
    url: "https://www.bloomberg.com/opinion/newsletters/2026-10-08/spectacular-earnings-growth-may-not-be-enough-to-keep-the-stock-rally-going",
  },
  {
    id: "nl-reuters-tradingday-stocksbondsdelicatedance-20261007",
    publication: "Reuters",
    author: "Jamie McGeever",
    series: "Trading Day",
    title: "Stocks, bonds in delicate dance",
    date: "2026-10-07",
    time: "22:00",
    summary: "Fed minutes raise questions.",
    url: "https://www.reuters.com/newsletters/trading-day",
  },
  {
    id: "nl-preqin-firstclose-specialaladdinclientforum-20261007",
    publication: "Preqin",
    author: null,
    series: "First Close",
    title: "Special issue from the Aladdin Client Forum",
    date: "2026-10-07",
    time: "22:09",
    summary: "AI tops the agenda as investors, asset managers and advisors gather in New York.",
    url: "https://go.preqin.com/webmail/909852/2196840722/10a07fc888799ba93601ccf55d4c7de31840aed202839f3c768c45aa7be76665",
  },
  {
    id: "nl-ms-fiveideas-healthcaregrowthdrivers-20261007",
    publication: "Morgan Stanley",
    author: null,
    series: "Five Ideas",
    title: "Healthcare’s Next Growth Drivers",
    date: "2026-10-07",
    time: "21:26",
    summary: "How healthcare leaders are navigating patent expirations, M&A and AI adoption to shape the industry’s future.",
    url: "https://www.morganstanley.com/ideas",
  },
  {
    id: "nl-bbg-moneystuff-esggetsmoreillegal-20261007",
    publication: "Bloomberg",
    author: "Matt Levine",
    series: "Money Stuff",
    title: "Money Stuff: ESG Gets More Illegal",
    date: "2026-10-07",
    time: "19:20",
    summary: "ESG, 401ks, universe.",
    url: "https://bloom.bg/4AT3Ss9",
  },
  {
    id: "nl-bbg-authoralert-rokosreturn-20261007",
    publication: "Bloomberg",
    author: "Nishant Kumar",
    series: "Author Alert",
    title: "Hedge Fund Rokos Returned 4.2% in Turbulent Month for Trading",
    date: "2026-10-07",
    time: "19:05",
    summary: "Chris Rokos's macro fund made 4.2% last month as many peers eked out meagre returns amid bond-market volatility.",
    url: "https://www.bloomberg.com/news/articles/2026-10-07/hedge-fund-rokos-returned-4-2-in-turbulent-month-for-trading",
  },
  {
    id: "nl-legalbusiness-alert-bootsdeal-20261007",
    publication: "Legal Business",
    author: null,
    series: "Legal Business Alert",
    title: "Quartet of firms lead on $8.9bn Boots deal",
    date: "2026-10-07",
    time: "16:42",
    summary: "Sale to Canadian investors' consortium sees UK retailer secure its second new owner in less than 18 months.",
    url: "https://www.legalbusiness.co.uk/law-firms/quartet-of-firms-lead-on-near-9bn-boots-deal/",
  },
  {
    id: "nl-thelawyer-podcast-manchestercityfeedingfrenzy-20261007",
    publication: "The Lawyer",
    author: null,
    series: "The Lawyer Podcast",
    title: "Manchester City - the lawyers' feeding frenzy has only just begun",
    date: "2026-10-07",
    time: "12:46",
    summary: "The team discuss the more unusual parts of the Manchester City judgment, plus how broadcasters react to legal news.",
    url: "https://www.thelawyer.com/the-lawyer-podcast-manchester-city-the-lawyers-feeding-frenzy-has-only-just-begun/",
  },
  {
    id: "nl-bbg-goingprivate-shortsellerscircling-20261007",
    publication: "Bloomberg",
    author: "Sinead Cruise",
    series: "Going Private",
    title: "Short-sellers circling",
    date: "2026-10-07",
    time: "11:20",
    summary: "Private credit draws speculators as volatility rocks fixed income assets.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-07/private-credit-shorts-rebound-as-bond-selloff-continues",
  },
  {
    id: "nl-preqin-firstclose-earlydaysaiadoption-20261007",
    publication: "Preqin",
    author: null,
    series: "First Close",
    title: "Early days as asset managers start to adopt AI",
    date: "2026-10-07",
    time: "11:25",
    summary: "The insider: Aladdin survey shows AI transformation still 'nascent' or 'emerging' for many investment managers.",
    url: "https://go.preqin.com/webmail/909852/2196510665/10a07fc888799ba93601ccf55d4c7de31840aed202839f3c768c45aa7be76665",
  },
  {
    id: "nl-bbg-wheretoinvest-where100000-20261007",
    publication: "Bloomberg",
    author: null,
    series: "Where to Invest",
    title: "Where to invest $100,000",
    date: "2026-10-07",
    time: "11:09",
    summary: "From defensive growth plays to a personal chef.",
    url: "https://www.bloomberg.com/features/how-to-invest-100k-q4-2026/",
  },
  {
    id: "nl-bbg-economicsdaily-indiantrilemma-20261007",
    publication: "Bloomberg",
    author: "Anup Roy",
    series: "Economics Daily",
    title: "Indian trilemma",
    date: "2026-10-07",
    time: "11:00",
    summary: "Global forces are narrowing the RBI's room to set policy independently.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-07/in-india-global-forces-are-narrowing-room-to-set-rate-policy-independently",
  },
  {
    id: "nl-bbg-marketsdaily-stocksfightgravity-20261007",
    publication: "Bloomberg",
    author: null,
    series: "Markets Daily",
    title: "Stocks fight gravity",
    date: "2026-10-07",
    time: "10:24",
    summary: "Plus, Taiwan is a big AI winner.",
    url: "https://www.bloomberg.com/news/newsletters/2026-10-07/stocks-are-due-for-a-gut-check-from-rates-oil-and-the-dollar",
  },
  {
    id: "nl-nonbillable-thecaseforpe-20261007",
    publication: "Non-Billable",
    author: null,
    series: null,
    title: "\u231b The case for PE",
    date: "2026-10-07",
    time: "09:06",
    summary: "And White & Case's retro rebrand sparks mixed reaction online.",
    url: "https://non-billable.beehiiv.com/p/the-case-for-pe",
  },
  {
    id: "nl-thelawyer-newsdaily-arsenalgcdeparts-20261007",
    publication: "The Lawyer",
    author: null,
    series: "News Daily",
    title: "Arsenal FC\u2019s veteran legal chief departs",
    date: "2026-10-07",
    time: "08:16",
    summary: "Arsenal FC's first-ever general counsel has left the club after 17 years.",
    url: "https://r.mail2.thelawyer.com/mk/mr/sh/28xHBT2OOm5aQrn4OwPr9qwiC32Ybr5qUL/XVfWnxNE1Gny",
  },
];
