// =============================================================================
// Newsletters — the reader's own aggregated email newsletters, surfaced in the
// Home news feed under a "Newsletter" label.
//
// Source: newsletters forwarded (via a Gmail filter) to the connected mailbox
// skaidrive2@gmail.com — Bloomberg (Money Stuff etc.), The Economist, Legal
// Business, JP Morgan, Thomson Reuters, Mailbrew and others. They are pulled
// from Gmail through the connector, parsed, and written here as feed items.
// This list is regenerated on each refresh.
//
// We keep only the headline, a one-line topic summary, the publication/author
// and the newsletter's own "read online" link — never the full article body.
// This deployment sits behind Cloudflare Access (single reader), so the list is
// personal to it.
//
// PUBLISHERS maps a sender address/domain to a display name (used by the refresh
// routine); extend it as new newsletters are added.
export const PUBLISHERS = {
  "news.bloomberg.com": "Bloomberg",
  "e.economist.com": "The Economist",
  "legalbusiness.co.uk": "Legal Business",
  "pb.jpmorgan.com": "JP Morgan Private Bank",
  "mail.sailthru.com": "Thomson Reuters",
  "thomsonreuters.com": "Thomson Reuters",
  "mailbrew.com": "Mailbrew",
  "cntraveller.com": "Condé Nast Traveller",
  "mail.nonbillable.co.uk": "Non-Billable",
  "newsletter.mail.gs.com": "Goldman Sachs",
  "businesspost.ie": "Business Post",
  "cf.com": "Chatham Financial",
};

export const NEWSLETTERS = [
  {
    id: "nl-econ-worldinbrief-20260801",
    publication: "The Economist",
    series: "The World in Brief",
    title: "The World in Brief: Spain’s latest migrant crisis",
    date: "2026-08-01",
    time: "04:27",
    summary: "Spain says over 50,000 migrants stormed the Ceuta border in a day, deploying troops after at least 57 died crossing, as FIFA scraps Gianni Infantino's plan to sell stakes in a World Cup venture.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-bbg-moneystuffpodcast-nokiddiepool-20260731",
    publication: "Bloomberg",
    author: "Matt Levine",
    series: "Money Stuff: The Podcast",
    title: "Money Stuff: The Podcast: No Kiddie Pool",
    date: "2026-07-31",
    time: "18:47",
    summary: "Guest co-host Silvia Killingsworth on the Situational Awareness situation, record dates, CVRs and weird retail volatility.",
    url: "https://bloom.bg/4nhTnYV",
  },
  {
    id: "nl-lb-anglotecklawyer-20260731",
    publication: "Legal Business",
    title: "Anglo American and Teck name top lawyer for $69bn mining mega-merger",
    date: "2026-07-31",
    time: "16:34",
    summary: "Former BHP group general counsel named on executive leadership team as mining merger gears up for completion.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMQyABrE8sIIN3CGpC/wv",
  },
  {
    id: "nl-bbg-wheretoinvest-elnino-20260731",
    publication: "Bloomberg",
    author: "John Stepek",
    series: "Where to Invest",
    title: "Where to Invest with El Niño",
    date: "2026-07-31",
    time: "14:34",
    summary: "How can you position a portfolio to weather its effects?",
    url: "https://www.bloomberg.com/news/articles/2026-07-31/where-to-invest-now-as-el-nino-hits-the-global-economy",
  },
  {
    id: "nl-lb-lathamcityhq-20260731",
    publication: "Legal Business",
    title: "'A mark of where we want to go' – Latham sets out growth plan for new City HQ",
    date: "2026-07-31",
    time: "14:14",
    summary: "London managing partner Ed Barnett on lateral priorities and what's next for the US firm's $1bn-revenue City operation.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMQyrEmdCMD5TdzxJR/wv",
  },
  {
    id: "nl-mailbrew-fridaybrew-20260731-6",
    publication: "Mailbrew",
    series: "Friday Brew",
    title: "Friday Brew #6",
    date: "2026-07-31",
    time: "13:58",
    summary: "Conspiracies and Ireland's stalled rail upgrade, Norges Bank's AI playbook for CRE, private credit's 'durable income' delusion, and Kevin Warsh on Fed guidance vs basis trades.",
    url: "https://app.mailbrew.com/stevedkennedy/friday-brew-03bEHcNb3hHB/6",
  },
  {
    id: "nl-jpm-rotationnotreckoning-20260731",
    publication: "JP Morgan Private Bank",
    series: "Top Market Takeaways",
    title: "Rotation, not reckoning: What's testing the AI trade?",
    date: "2026-07-31",
    time: "13:21",
    summary: "Investors are shifting away from artificial intelligence-related trades and into overlooked sectors as they seek proof of returns.",
    url: "https://go-pb.jpmorgan.com/v/MzkyLUhLQy04NzYAAAGjVxf3Ym9TUNggaFbLZmJOlH87oCgaCVdfsKSCwcUbPP-HxdxgLDPLJsODHyuCoAu4KBFlHcY=",
  },
  {
    id: "nl-bbg-parisedition-succession-20260731",
    publication: "Bloomberg",
    author: "Lionel Laurent",
    series: "Paris Edition",
    title: "Paris Edition: The succession question",
    date: "2026-07-31",
    time: "12:50",
    summary: "Billionaire Bernard Arnault's 'Merci' memo fails to address the key question of succession.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-31/billionaire-s-merci-memo-fails-to-address-the-key-question-of-succession",
  },
  {
    id: "nl-bbg-economicsdaily-japancurrencydogfight-20260731",
    publication: "Bloomberg",
    author: "Malcolm Scott",
    series: "Economics Daily",
    title: "Economics Daily: Japan’s currency dogfight",
    date: "2026-07-31",
    time: "12:02",
    summary: "Japan steps in with rare yen intervention as currency weakness complicates Takaichi’s policy path.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-31/yen-at-levels-when-top-gun-topped-box-office-sparks-currency-dogfight",
  },
  {
    id: "nl-bbg-goingprivate-mobileappdebt-20260731",
    publication: "Bloomberg",
    author: "Sinead Cruise",
    series: "Going Private",
    title: "Going Private: Mobile app debt demand carves out high-risk private credit niche",
    date: "2026-07-31",
    time: "12:01",
    summary: "Direct lenders offer no-growth, no-repayment loans to creators seeking the next cult concept.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-31/mobile-app-debt-demand-carves-high-risk-private-credit-niche",
  },
  {
    id: "nl-bbg-marketsdaily-weekofdrama-20260731",
    publication: "Bloomberg",
    series: "Markets Daily",
    title: "Markets Daily: A week of drama",
    date: "2026-07-31",
    time: "11:46",
    summary: "Market swings are turning severe.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-31/traders-got-hit-with-drama-everywhere-this-week",
  },
  {
    id: "nl-gs-briefings-fedoutlook-20260731",
    publication: "Goldman Sachs",
    series: "Briefings",
    title: "The Outlook for the Fed",
    date: "2026-07-31",
    time: "11:46",
    summary: "Bond markets interpreted Wednesday's Fed meeting as dovish, but Goldman Sachs Research expects the central bank to keep rates steady throughout 2026.",
    url: "https://www.goldmansachs.com/briefings",
  },
  {
    id: "nl-nonbillable-macfarlanespep-20260731",
    publication: "Non-Billable",
    title: "A 'satisfactory' £3.1m",
    date: "2026-07-31",
    time: "09:05",
    summary: "Macfarlanes posts a 'satisfactory' £3.1m PEP as Wachtell loses a six-partner team led by co-chair William Savitt to Gibson Dunn and Legora buys litigation AI startup Wexler.",
    url: "https://non-billable.beehiiv.com/p/how-cc-broke-into-new-york-s-private-equity-elite-1",
  },
  {
    id: "nl-bbg-morningbriefingeurope-20260731",
    publication: "Bloomberg",
    author: "Samson Ellis",
    series: "Morning Briefing Europe",
    title: "Situational Awareness Weighed Private Stake Sales Before Citadel",
    date: "2026-07-31",
    time: "08:11",
    summary: "Situational Awareness tried to sell private stakes in a scramble to raise cash before striking a deal with Citadel, as global tech stocks rally and Trump announces a deal for Hamas to disarm.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-31/situational-awareness-weighed-private-stake-sales-before-citadel",
  },
  {
    id: "nl-cnt-restaurantofweek-20260731",
    publication: "Condé Nast Traveller",
    series: "Restaurant of the Week",
    title: "The best new restaurant in London is...",
    date: "2026-07-31",
    time: "08:00",
    summary: "This week's pick: an East London BBQ opening serving sticky Sichuan-glazed beef short ribs.",
    url: "https://link.cntraveller.com/view/69aad66ceb56cb62e611cb3brvhsr.v6o/14e0165a",
  },
  {
    id: "nl-econ-worldinbrief-20260731",
    publication: "The Economist",
    series: "The World in Brief",
    title: "The World in Brief: Hamas agrees to disarm",
    date: "2026-07-31",
    time: "06:40",
    summary: "A US-brokered Board of Peace deal has Hamas agreeing to disarm fully, contingent on an Israeli withdrawal from Gaza, as Anthropic says it caught its own models breaking out of testing environments.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-reuters-tradingday-commsintervention-20260730",
    publication: "Thomson Reuters",
    author: "Jamie McGeever",
    series: "Trading Day",
    title: "Communication, intervention & liquidation",
    date: "2026-07-30",
    time: "22:02",
    summary: "Wall Street rallied on AI optimism as Microsoft surged and the yen jumped on suspected BOJ intervention, but McGeever argues the bond market isn't buying Fed Chair Warsh's inflation resolve.",
    url: "https://www.reuters.com/commentary/reuters-open-interest/bond-market-isnt-buying-what-fed-chair-warsh-is-selling-2026-07-30/",
  },
  {
    id: "nl-bbg-authoralert-nkumar-20260731",
    publication: "Bloomberg",
    author: "Nishant Kumar",
    title: "The 24-Hour Race to Salvage Situational Awareness' Souring Bets",
    date: "2026-07-31",
    time: "01:00",
    summary: "The frantic scramble to shore up positions after the AI-forecasting fund manager hailed as a young 'Nostradamus' saw his bold predictions sour.",
    url: "https://www.bloomberg.com/news/articles/2026-07-30/the-24-hour-race-to-salvage-situational-awareness-souring-bets",
  },
  {
    id: "nl-bbg-moneystuff-situationdeteriorated-20260730",
    publication: "Bloomberg",
    author: "Matt Levine",
    series: "Money Stuff",
    title: "Money Stuff: The Situation Deteriorated",
    date: "2026-07-30",
    time: "19:03",
    summary: "Elections, PBCs, Ionic, WLFI.",
    url: "https://bloom.bg/44TMQvs",
  },
  {
    id: "nl-bbg-authoralert-nkumar-20260730",
    publication: "Bloomberg",
    author: "Nishant Kumar",
    title: "Hedge Fund Trader Kassam Readies a Billion-Dollar Millennium Cub",
    date: "2026-07-30",
    time: "17:13",
    summary: "Farzad Kassam, a senior macro portfolio manager at Millennium Management, is preparing to start his own outfit with backing from Izzy Englander's multistrategy firm.",
    url: "https://www.bloomberg.com/news/articles/2026-07-30/hedge-fund-trader-kassam-readies-a-billion-dollar-millennium-cub",
  },
  {
    id: "nl-bbg-economicsdaily-warshbronx-20260730",
    publication: "Bloomberg",
    author: "Chris Anstey",
    series: "Economics Daily",
    title: "Economics Daily: Warsh’s ‘Bronx cheer’",
    date: "2026-07-30",
    time: "11:08",
    summary: "The Fed kept interest rates unchanged, causing investors to dump 30-year Treasury bonds.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-30/kevin-warsh-delivers-a-perplexing-fed-briefing-and-gets-a-bronx-cheer",
  },
  {
    id: "nl-bbg-marketsdaily-warshresolve-20260730",
    publication: "Bloomberg",
    series: "Markets Daily",
    title: "Markets Daily: Bond traders doubt Fed’s resolve",
    date: "2026-07-30",
    time: "10:35",
    summary: "Plus, a look at rising CDS levels in big tech.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-30/traders-are-doubting-warsh-s-resolve-on-inflation",
  },
  {
    id: "nl-lb-eqtintertek-20260730",
    publication: "Legal Business",
    title: "Freshfields and Slaughters set to share £40m-plus fees on EQT-Intertek deal",
    date: "2026-07-30",
    time: "09:58",
    summary: "CC, Linklaters and Simpson Thacher also in the mix on Swedish PE giant's £10.9bn acquisition of FTSE 100 company.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMQxNmsNkfb2dk3UFR/wv",
  },
  {
    id: "nl-bbg-morningbriefingeurope-20260730",
    publication: "Bloomberg",
    author: "Abhishek Shanker and Victoria Batchelor",
    series: "Morning Briefing Europe",
    title: "US Launches Fresh Strikes on Iran Hitting Military Targets",
    date: "2026-07-30",
    time: "07:40",
    summary: "The US launches a fresh wave of strikes on Iran; Andy Burnham unveils an £8.4bn Dreadnought submarine investment; and a family feud threatens Leonardo Del Vecchio's €40bn empire.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-30/us-launches-fresh-strikes-on-iran-hitting-military-targets",
  },
  {
    id: "nl-econ-worldinbrief-20260730",
    publication: "The Economist",
    series: "The World in Brief",
    title: "The World in Brief: America retaliates against Iran",
    date: "2026-07-30",
    time: "05:48",
    summary: "America struck Iran's southern provinces after a missile attack on US forces in Jordan, sending Brent crude toward $90, as the Fed held rates steady and Meta's profits sank 14%.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-bbg-pointsofreturn-20260730",
    publication: "Bloomberg",
    author: "John Authers",
    series: "Points of Return",
    title: "Warsh needs to do better than ‘I won’t tell you’",
    date: "2026-07-30",
    time: "05:25",
    summary: "The FOMC held rates as three members voted for a hike, and Warsh's baffling press conference drove the sharpest yield-curve steepening in a year as the Nasdaq 100 sank more than 10% below its peak.",
    url: "https://bloom.bg/4hEHA6n",
  },
  {
    id: "nl-reuters-tradingday-aicrash-20260729",
    publication: "Thomson Reuters",
    author: "Jamie McGeever",
    series: "Trading Day",
    title: "All Warshed up",
    date: "2026-07-29",
    time: "21:01",
    summary: "US shares tumbled and long yields hit multi-decade peaks after the Fed held rates, as the South Korean stock rout deepened on SK Hynix earnings.",
    url: "https://www.reuters.com/commentary/reuters-open-interest/could-an-ai-market-crash-rival-2000-or-2008-unlikely-2026-07-29/",
  },
  {
    id: "nl-bbg-moneystuff-spacexcrash-20260729",
    publication: "Bloomberg",
    author: "Matt Levine",
    series: "Money Stuff",
    title: "Money Stuff: SpaceX Crash Insurance",
    date: "2026-07-29",
    time: "18:57",
    summary: "Structured notes, sports, ETFs, slop.",
    url: "https://bloom.bg/4h4BQCM",
  },
  {
    id: "nl-bbg-authoralert-nkumar-20260729",
    publication: "Bloomberg",
    author: "Nishant Kumar",
    title: "Millennium’s New Capital Raise Targets a Record $20 Billion",
    date: "2026-07-29",
    time: "16:40",
    summary: "Millennium Management is in talks with investors to raise an unprecedented $20 billion to reinforce its stronghold in the multistrategy hedge fund industry.",
    url: "https://www.bloomberg.com/news/articles/2026-07-29/millennium-s-new-capital-raise-targets-a-record-20-billion",
  },
  {
    id: "nl-lb-kuwaitoiljv-20260729",
    publication: "Legal Business",
    title: "Top UK and US firms advise major asset management trio on $16bn Kuwait oil JV",
    date: "2026-07-29",
    time: "14:50",
    summary: "Blackstone, Brookfield, and KKR line up for deal that marks Kuwait's largest ever FDI.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMQxvshWiTm3L1kqgi/wv",
  },
  {
    id: "nl-bbg-goingprivate-cerberuspentagon-20260729",
    publication: "Bloomberg",
    author: "Sinead Cruise",
    series: "Going Private",
    title: "Going Private: Cerberus alum remodels Pentagon’s $1 trillion defense spending",
    date: "2026-07-29",
    time: "12:18",
    summary: "From Wall Street to War Room: Stephen Feinberg ushers in new era for US national security.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-29/private-equity-alum-remodels-pentagon-s-spending-from-within",
  },
  {
    id: "nl-bbg-economicsdaily-fedwarsh-20260729",
    publication: "Bloomberg",
    author: "Chris Anstey",
    series: "Economics Daily",
    title: "Fed Watchers Gird for a Lesson on Reading Warsh in High-Stakes Rate Call",
    date: "2026-07-29",
    time: "12:00",
    summary: "The Fed is expected to hold interest rates steady, but market participants aren't ruling out a hike.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-29/fed-watchers-gird-for-a-lesson-on-reading-warsh-in-high-stakes-rate-call",
  },
  {
    id: "nl-bbg-marketsdaily-fedwarsh-20260729",
    publication: "Bloomberg",
    series: "Markets Daily",
    title: "Markets Brace for One of the Most Uncertain Fed Days in Years",
    date: "2026-07-29",
    time: "11:16",
    summary: "Welcome to the new tight-lipped era under Warsh.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-29/markets-brace-for-one-of-the-most-uncertain-fed-days-in-years",
  },
  {
    id: "nl-lb-macfarlanespep-20260729",
    publication: "Legal Business",
    title: "Macfarlanes closes in on £400m as PEP stays flat",
    date: "2026-07-29",
    time: "10:50",
    summary: "Macfarlanes posts a 4.9% revenue increase to close in on £400m as profit per equity partner stays flat in a 'transitional year'.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMQx4B1ELRIodQsNan/wv",
  },
  {
    id: "nl-nonbillable-ccnype-20260729",
    publication: "Non-Billable",
    title: "How CC broke into New York's private equity elite",
    date: "2026-07-29",
    time: "09:04",
    summary: "Clifford Chance becomes the first non-US firm to break into New York private equity buyout rankings, and Mayer Brown doubles down on London private capital.",
    url: "https://non-billable.beehiiv.com/p/b-c787",
  },
  {
    id: "nl-lb-felsensteingodfather-20260729",
    publication: "Legal Business",
    title: "Latham's Oliver Felsenstein on The Godfather, client call car crashes and becoming a PE lawyer by accident",
    date: "2026-07-29",
    time: "09:01",
    summary: "Germany private equity heavyweight Oliver Felsenstein reflects on decades of dealmaking, from dreams of becoming Don Corleone's consigliere to his retirement plans for a champagne bar.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMQx07tWw1KtFt6cca/wv",
  },
  {
    id: "nl-bbg-morningbriefingeurope-20260729",
    publication: "Bloomberg",
    author: "Victoria Batchelor",
    series: "Morning Briefing Europe",
    title: "UBS and Deutsche Bank Deliver Strong Earnings",
    date: "2026-07-29",
    time: "07:33",
    summary: "UBS and Deutsche Bank post solid earnings as oil jumps on fresh Middle East fighting and the chip-led stock rout deepens.",
    url: "https://www.bloomberg.com/news/newsletters/2026-07-29/ubs-and-deutsche-bank-deliver-strong-earnings",
  },
  {
    id: "nl-econ-worldinbrief-20260729",
    publication: "The Economist",
    series: "The World in Brief",
    title: "The World in Brief: America thwarts \"surprise\" Iranian attack",
    date: "2026-07-29",
    time: "06:16",
    summary: "America says it intercepted a \"surprise\" Iranian missile attack in the Gulf and bans imports of humanoid robots, as SK Hynix profits miss forecasts despite a 557% jump.",
    url: "https://www.economist.com/the-world-in-brief",
  },
  {
    id: "nl-bbg-pointsofreturn-20260729",
    publication: "Bloomberg",
    author: "John Authers",
    series: "Points of Return",
    title: "The Magnificent Seven are riding into the sunset",
    date: "2026-07-29",
    time: "05:04",
    summary: "The equal-weighted S&P 500 hits an all-time high and overtakes the Nasdaq 100 (down almost 10% from its peak) as WTI crude jumps 5% on an Iranian attack ahead of Wednesday's FOMC decision.",
    url: "https://bloom.bg/3TuSodi",
  },
  {
    id: "nl-lb-gibsondunnwachtell-20260728",
    publication: "Legal Business",
    title: "Six-partner Wachtell team led by co-chair leaves for Gibson Dunn",
    date: "2026-07-28",
    time: "20:20",
    summary: "Exec committee co-chair Bill Savitt leads Wachtell group moving to Gibson Dunn in latest in series of once-rare departures from elite US firm.",
    url: "https://email.legalbusiness.co.uk/q/12H5apPMQwVDWegbNsmPjenI/wv",
  },
];
